### ISSUE TITLE
Version not updated and broken links still available

### ISSUE THREAD

**Issue by BenAkor** [criteo-cookbooks/ms_dotnet#105]
The metadata has not been updated hence the broken links are still in the cookbook package helper in the chef supermarket. Could you please update the version and push the new cookbook version to the chef supermarket?

**Comment by Annih** [comment]
Hello @BenAkor thanks for the report, please be assured we are working on this, we need to fix the CI first then we'll release a new version with the fix.

**Comment by jakauppila** [comment]
@Annih Is #106 the last thing you're waiting on before cutting a new release?

**Comment by Annih** [comment]
Hello @jakauppila yes! sorry about that huge delay!

**Comment by jakauppila** [comment]
Hi @Annih I see that PR has been merged, any chance for a new release to be published?
