### ISSUE TITLE
Installation of .NET 4.6 on Windows 2012 R2 requires Windows updates

### ISSUE THREAD

**Issue by olivierlemasle** [criteo-cookbooks/ms_dotnet#24]
Installation of .NET 4.6 with this cookbook does not work on a Windows 2012 R2 eval box without windows updates.

The box has been created using "eval-win2012r2-standard" from https://github.com/boxcutter/windows, and has no windows update installed.

The `ms_dotnet_framework` fails. If I run manually the .NET installer, I see that some updates ([KB2919355](https://support.microsoft.com/en-us/kb/2919355)) are required:

![virtualbox_amysta-cookbook_web_1466810330379_40128_25_06_2016_01_33_48](https://cloud.githubusercontent.com/assets/628140/16356630/98f3242a-3adf-11e6-86a2-cd1e0c9f8f0e.png)

Do you think it is possible to install required Windows updates automatically with this Chef cookbook?

Or do I have to include the required Windows updates in my Windows box? Do you know if there are other requirements to install .NET on specific Windows versions? It would be great to list the requirements in this cookbook `README.md`.

**Comment by Annih** [comment]
Hello @olivierlemasle 

Thanks for your feedback, indeed I only test with boxes including this important update.
That's the kind of issue I wanted to fix before releasing the version 3.0.0; I think I have a "pretty" implementation for this case.

We just need to install the [following msu](https://download.microsoft.com/download/D/B/1/DB1F29FC-316D-481E-B435-1654BA185DCF/Windows8.1-KB2919355-x64.msu)

I'll keep you posted.

Regards.

**Comment by Annih** [comment]
@olivierlemasle could you give me the source of your box?
I tried mwrock one, but it has a lot of updates on it.

**Comment by Annih** [comment]
OK I got the opentable box, which has no updates :)
I think I forgot to add the prerequisites for the prerequisites ^^

https://support.microsoft.com/en-us/kb/2919442

**Comment by olivierlemasle** [comment]
Hi @Annih,

I used the box eval-win2012r2-standard from https://github.com/boxcutter/windows.
