### ISSUE TITLE
package_sources not working

### ISSUE THREAD

**Issue by Jakauppila** [criteo-cookbooks/ms_dotnet#26]
I'm trying to specify a custom package source per the doc and am getting a SyntaxError at runtime:

```
ms_dotnet_framework '4.6.1' do
  action            :install
  include_patches   false
  package_sources   { beaa901e07347d056efe04e8961d5546c7518fab9246892178505a7ba631c301: 'https://s3.amazonaws.com/****************/dotnet/distributions/NDP461-KB3102436-x86-x64-AllOS-ENU.exe' }
  require_support   true
end
```
```
SyntaxError
-----------
C:/local-mode-cache/cache/cookbooks/*********/recipes/installDotNet.rb:25: syntax error, unexpected ':', expecting '}'
...18fab9246892178505a7ba631c301": 'https://s3.amazonaws.com/se...
...                               ^
```

Is the syntax slightly different?

**Comment by Jakauppila** [comment]
Looks like it doesn't like the space between the two values in package_sources:
```
ms_dotnet_framework '4.6.1' do
  action            :install
  include_patches   false
  package_sources   { beaa901e07347d056efe04e8961d5546c7518fab9246892178505a7ba631c301:'https://s3.amazonaws.com/****************/dotnet/distributions/NDP461-KB3102436-x86-x64-AllOS-ENU.exe'}
  require_support   true
end
```

Also, it looks like the package uploaded to the Supermarket is incomplete, it's missing the providers and resources folders.

(Supermarket on the left, Github on the right)

![ms_dotnet_packaged](https://cloud.githubusercontent.com/assets/4100127/16739685/fd5b837a-4760-11e6-9cc3-d8eaa6aafb6b.JPG)

**Comment by Annih** [comment]
Hello @Jakauppila 

First of all thanks for your feedback, it seems that I used a bad syntax in the doc.
You need to quote the sha256 - and dependings on the ruby version you should use the rocket operator:

```ruby
ms_dotnet_framework '4.6.1' do
  package_sources   { 'beaa901e07347d056efe04e8961d5546c7518fab9246892178505a7ba631c301' => 'https://s3.amazon.com' }
end
```

About the supermarket point, that's totally normal. I'm currently trying to fix all that kind of issues before releasing a new version :)

Let me know if that fixes your issue.

Regards!
