### ISSUE TITLE
Possible to reboot as part of install?

### ISSUE THREAD

**Issue by bveselka** [criteo-cookbooks/ms_dotnet#30]
Is it possible for me to have my usage cause a reboot?  It doesn't currently and I've found that 4.6.1 needs that for the server to truly complete the install process.

**Comment by Matasx** [comment]
.Net 4.6.1 and 4.6.2 may need to reboot the system after installation. But it doesn't do the actual reboot. It rather just sets the reboot pending flag in windows registry. If you need to perform reboot prior installing any other service, you can use something like this:

```
reboot 'Perform pending reboot' do
  action :reboot_now
  reason 'Perform pending reboot.'
  only_if { reboot_pending? }
end
```

Note that reboot is built-in resource and reboot_pending? is part of the Recipe DSL.

**Comment by bveselka** [comment]
That got it!  Thanks for the clarification!
