### ISSUE TITLE
dotnet3 has the wrong feature name in the library file for server 2012r2

### ISSUE THREAD

**Issue by joldham1023** [criteo-cookbooks/ms_dotnet#40]
Server 2012r2 expects that the feature name is NetFx3ServerFeatures, and this cookbook is setting it to NetFx3.

This is the logic from version 2.6.0:

if nt_version >= 6.0
    # Windows Server 2012 and earlier have Server features
    if nt_version >= 6.2 && ::Windows::VersionHelper.server_version?(node)
      feature_name = 'NetFx3ServerFeatures'
    else
      feature_name = 'NetFx3'
    end

The logic in the current library file for 3.5 is:

def feature_names
      @feature_names ||= nt_version >= 6.0 ? %w(NetFx3) : []
end

**Comment by jmauro** [comment]
Hello @joldham1023,

Sorry for not answering right away, we will look the issue and let you know as soon as possible.

Regards,
JM

**Comment by jmauro** [comment]
Hello @joldham1023,

The NetFx3 (or Net-Framework-Core) feature is the core feature installing the binaries;
NetFx3ServerFeatures (Net-Framework-Features) is the Feature group (the parent) of NetFx3 features, it doesn't install anything.

Does that answer your issue?

Regards,
JM
