### ISSUE TITLE
new version of .NET framework 4.7 

### ISSUE THREAD

**Issue by lbn-chef-team** [criteo-cookbooks/ms_dotnet#61]
Hello,

There is a new available version of .NET: 
https://www.microsoft.com/en-us/download/details.aspx?id=55167

it will be great to add this version to this cookbook.

Regards,

**Comment by Annih** [comment]
Hello @lbn-chef-team

You are right that'll be great :D
We'll do our best to add it ASAP.

**Comment by jmauro** [comment]
Hello @lbn-chef-team, 

If you have time we would be glad to review any PR with this new dot net framework.
We will do our best to release it but if your team need this version ASAP we don't want to be blockers for you :). 

BTW, thx for the report. 

Regards, 
JM

**Comment by jmauro** [comment]
Fix with https://github.com/criteo-cookbooks/ms_dotnet/pull/62
