### ISSUE TITLE
Installation behaves as if .NET already installed.

### ISSUE THREAD

**Issue by frankbarbarino** [criteo-cookbooks/ms_dotnet#70]
I was trying to install 4.7 following the example:
Install .NET 4.5.2 from custom sources
(except providing a valid checksum and download url)
4.7 has not been installed yet, but it never gets to the download.   The run indicates:

  * ms_dotnet_framework[install] action install (up to date)

**Comment by Annih** [comment]
Hello @frankbarbarino 

We need more details to help you :)
Could you tell me which version of the cookbook you use ? from supermarket or github?
Can you give us an example of the recipe you used, and the attributes/properties values setup?

Regards

**Comment by frankbarbarino** [comment]
I am using version 3.2.1 of the cookbook from github.
my cookbook attached.


On Wed, Jul 12, 2017 at 3:11 PM, Baptiste Courtois <notifications@github.com

**Comment by frankbarbarino** [comment]
Are you able to reproduce the issue using the supplied rb files?

**Comment by taliesins** [comment]
This PR: #72 may solve your problem. This was the behavior I was experiencing.

**Comment by Annih** [comment]
@frankbarbarino could you confirm you were on one of the "fixed" windows version?

**Comment by taliesins** [comment]
Yes I have run this on Windows Server 2012R2 and it works. 

You can see that the references are there for download on those specific platforms. This is how I selected which missing packages to add.

**Comment by Annih** [comment]
@frankbarbarino version 4.0.0 has been released with @taliesins fix.
Feel free to reopen if you still encounter this issue.
