### ISSUE TITLE
install .Net 3.5 on win server 2016, failed

### ISSUE THREAD

**Issue by aidda** [criteo-cookbooks/ms_dotnet#71]
I am trying to install .Net 3.5 on windows server 2016, but I recievde this error:
`      The operation is complete but NetFx3 feature was not enabled.
       
       
       
       
       
        The DISM log file can be found at C:\Windows\Logs\DISM\dism.log
        STDERR: 
        ---- End output of C:\Windows\system32\dism.exe /online /enable-feature /featurename:NetFx3 /norestart  /All ----
        Ran C:\Windows\system32\dism.exe /online /enable-feature /featurename:NetFx3 /norestart  /All returned 50
       
        Resource Declaration:
        ---------------------
        # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/windows/resources/feature.rb
       
         60:       windows_feature_dism new_resource.name do
         61:         action desired_action
         62:         feature_name new_resource.feature_name
         63:         source new_resource.source if new_resource.source
         64:         all new_resource.all
         65:       end
         66:     when :windows_feature_servermanagercmd
       
        Compiled Resource:
        ------------------
        # Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/windows/resources/feature.rb:60:in `run_default_provider'
       
        windows_feature_dism("NetFx3") do
          action [:install]
          updated true
          updated_by_last_action true
          default_guard_interpreter :default
          declared_type :windows_feature_dism
          cookbook_name "ms_dotnet"
          feature_name "NetFx3"
          all true
        end
       
        System Info:
        ------------
        chef_version=13.1.31
        platform=windows
        platform_version=10.0.14393
        ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
        program_name=C:/opscode/chef/bin/chef-client
        executable=C:/opscode/chef/bin/chef-client
       
       
             ================================================================================
             Error executing action `install` on resource 'windows_feature[NetFx3]'
             ================================================================================
       
             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             windows_feature_dism[NetFx3] (C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/windows/resources/feature.rb line 60) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 42, 127, 3010], but received '50'
             ---- Begin output of C:\Windows\system32\dism.exe /online /enable-feature /featurename:NetFx3 /norestart  /All ----
             STDOUT: Deployment Image Servicing and Management tool
       
             Version: 10.0.14393.0
`

**Comment by Annih** [comment]
Hello @aidda 

As for Windows Server 2012R2, Windows Server 2016 setup does not include .NET3 sources.
You need to specify where to find the sources. See https://github.com/criteo-cookbooks/ms_dotnet#install-net-35-sp1-using-a-windows-unc-share
