### ISSUE TITLE
ms_dotnet 4.7 with Windows 6.1.7600 needs SP1 prerequisites

### ISSUE THREAD

**Issue by nadobando** [criteo-cookbooks/ms_dotnet#76]
Hi 
I just figured out another constraint for this cookbook... 
in the section of prerequisites for windows 6.1 you should include Service Pack 1 as a prerequirment

Thanks, Nadobando.

**Comment by Annih** [comment]
You are right @nadobando I'll update the README accordingly.
Thanks for your feedback
