### ISSUE TITLE
Expected process to exit with [0, 3010], but received '16389' (client 12.21.3/ Windows 2008 R2)

### ISSUE THREAD

**Issue by mschoelen** [criteo-cookbooks/ms_dotnet#79]
Running **arcgis-enterprise::system** results in a fatal error (16389). ms_dotnet is a dependency for this cookbook. 

Chef-client version: **12.21.3**
Client was installed via bootstrap on **Windows Server 2008 R2**

**Environment:**

`{
  "msdotnet": {
    "v4": {
      "package_sources": "https://download.microsoft.com/download/1/6/7/167F0D79-9317-48AE-AEDB-17120579F8E2/NDP451-KB2858728-x86-x64-AllOS-ENU.exe"
    }
  },

  "arcgis": {
    "version": "10.5.1",
    "data_store": {
      "data_dir": "C:\\arcgisdatastore"
    },
    "server": {
      "directories_root": "C:\\arcgisserver"
    },
    "portal": {
      "data_dir": "C:\\arcgisportal"
    }
  }
}`

**Run list:**

  "run_list":[
    "recipe[arcgis-enterprise::system]",    
    "recipe[arcgis-enterprise::server]",
    "recipe[arcgis-enterprise::federation]"
  ]

Error message:

`SERV01.website.com================================================================================←[0m
SERV01.website.com  ←[31mError executing action `install` on resource 'ms_dotn
et_framework[4.5.1]'←[0m
SERV01.website.com ==========================================================
======================←[0m`

`SERV01.website.com [2018-01-18T11:06:37-05:00] FATAL: Mixlib::ShellOut::Shell
CommandFailed: arcgis_enterprise_server[Install System Requirements:server] (ar
cgis-enterprise::server line 31) had an error: Mixlib::ShellOut::ShellCommandFa
iled: ms_dotnet_framework[4.5.1] (ms_dotnet::ms_dotnet4 line 24) had an error:
Mixlib::ShellOut::ShellCommandFailed: windows_package[Microsoft .NET Framework
4.5.1] (c:/chef/cache/cookbooks/ms_dotnet/resources/framework.rb line 77) had a
n error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0
, 3010], but received '16389'`

I'm not entirely sure where to start with debugging this. It appears to be related to the MS .NET 4.5.1 configuration.

**Comment by Annih** [comment]
Hello @mschoelen thanks for reporting this issue. I saw that you also created Esri/arcgis-cookbook#126, and that even a manual install is failing (due to .NET 4.6) this is a good start.

The error *16389* or *0x80004005* is well known on the internet, but it may have multiple root cause:
* https://social.technet.microsoft.com/Forums/en-US/4808233e-1410-4305-a8d1-0e88f3a6fdc8/net-451-install-only-works-when-running-on-a-ui-session?forum=configmanagerapps
* http://www.myitforum.com/forums/Net-452-Fails-with-ExitCode-16389-m243437.aspx

To clarify the situation could you please first describe how Chef is running:
* Locally on the server as a Service
* Locally on the server as a Scheduled task
* Remotely via "knife bootstrap" or something similar

**Comment by mschoelen** [comment]
@Annih , Thanks for looking into this. Agreed on the multiple root cause-- although most solutions revolve around modifying SCCM parameters, rather than something that could be adjusted in Chef attributes.

To your points:
-We have Chef DK installed on a workstation. It is communicating with Chef Server on a different machine. We use knife winrm to run Chef-client.
-Chef client was installed via "knife bootstrap" command, below.

`C:\Users\username\.chef> knife bootstrap windows winrm 123.456.78 --bootstrap-version 12.21.3  --winrm-user DOMAIN\username --winrm-password 'PASSWORD' --node-name node01`

**Comment by Annih** [comment]
Could you try to run Chef manually and locally on the server?

**Comment by mschoelen** [comment]
@Annih , I ran `chef-client` directly on the node, and it ran completely fine. It was able to `- install version latest of package Microsoft .NET Framework 4.5.1`. It was also able to recognize that .NET 4.5.1 was already installed. 

I tried running it from ChefDK on my workstation again, and received the same error message (`Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0 , 3010], but received '16389'`)

Is it a permissions thing?

**Comment by Annih** [comment]
Hello @mschoelen 

Yes it is related to permissions in a remote context. When creating a remote session with WinRM (used by knife bootstrap), your permission are a bit restricted.

I tried to describe some workaround in the **Known issues** section of the README:

https://github.com/criteo-cookbooks/ms_dotnet#known-issues

Let me know if you need more help to fix your issue.
