### ISSUE TITLE
Release for .NET 4.7.1

### ISSUE THREAD

**Issue by smudgerdan** [criteo-cookbooks/ms_dotnet#80]
Can you please release a new version of this cookbook to Supermarket so the feature to install .NET 4.7.1 can be used.

Thanks.

**Comment by Annih** [comment]
@smudgerdan sorry but the .NET 4.7.1 is still not completely supported.
We'll release once #82, #83 & #84 will be merged.

Thanks for your patience.

**Comment by chrisdrobison** [comment]
Those 3 things look to be merged. Are you planning on releasing this soon then?

**Comment by Annih** [comment]
done :)
