### ISSUE TITLE
Missing prereq for 4.7.1 on Server 2012R2

### ISSUE THREAD

**Issue by jakauppila** [criteo-cookbooks/ms_dotnet#90]
I was updating our wrapper cookbook from 4.0.1 to 4.2.0 and in testing (with box 'opentable/win-2012r2-standard-amd64-nocm') found a missing prereq when attempting to install 4.7.1:

![image](https://user-images.githubusercontent.com/4100127/41934608-c37e2836-794c-11e8-8c4a-3e1a72609a52.png)

**Comment by jmauro** [comment]
Hello @jakauppila 

This message means that you need to reboot the server before doing anything else.
Do it and let us know if the problem persists.

Regards,
JM

**Comment by jakauppila** [comment]
Same issue for 4.7.2 as well:

![image](https://user-images.githubusercontent.com/4100127/41985518-24bca42c-79f9-11e8-9d7f-e474f0fec7ed.png)
