### ISSUE TITLE
.net 4.7.2 installer 404

### ISSUE THREAD

**Issue by jcuzzi** [criteo-cookbooks/ms_dotnet#91]
The default source URL for the 4.7.2 installer is not working. It should be updated to this:
https://download.microsoft.com/download/6/E/4/6E48E8AB-DC00-419E-9704-06DD46E5F81D/NDP472-KB4054530-x86-x64-AllOS-ENU.exe

**Comment by nemesis519** [comment]
Confirming this is an issue for us as well.

@Annih Any chance of getting the URL updated?

**Comment by nemesis519** [comment]
Adding MS footnote  -

The package installer (NDP472-KB4054530-x86-x64-AllOS-ENU.exe) was updated on July 10, 2018. If you downloaded the installer before July 10, 2018, we recommend that you download the latest version (4.7.3081.0) of the installer to get the additional fixes included in the update.

**Comment by Annih** [comment]
OK, I can easily change the URL, but the issue is that current code is not able to detect that we are not up-to-date since they reused the same release id :/

**Comment by nemesis519** [comment]
I can work with that in my use case, will just kill off old instances.

**Comment by nemesis519** [comment]
@Annih & @aae42  Thank you for the fix. Is there a timeline for when this will be pushed to Chef Supermarket?

**Comment by gdavison** [comment]
@Annih any chance you could make a 4.2.1 release with the updated path for .Net 4.7.2? This is a blocker for us

**Comment by Annih** [comment]
Done!
