### ISSUE TITLE
 Unsatisfiable Run List Item on ms_dotnet

### ISSUE THREAD

**Issue by cp713a** [criteo-cookbooks/ms_dotnet#95]
Hi,

I downloaded this ms_dotnet package and wanted to use on our Chef Server due to certain .msi packages need to require .NET package framework to run/install.  But, I encountered this when run this cookbook.  It keeps saying unable to satisfy constraints on package windows.  For instance, a .msi package requires to have .NET framework version 2.0 to run.

The machine/node I am using is a Windows10. 

Here's a complete error:

 Unsatisfiable Run List Item
Unable to satisfy constraints on package windows, which does not exist, due to solution constraint (ms_dotnet >= 0.0.0). Solution constraints that may result in a constraint on windows: [(ms_dotnet = 4.2.1) -> (windows >= 2.1.0)]

and here's the output from a stacktrace file:

Generated at 2019-02-12 10:52:59 -0800
Net::HTTPServerException: 412 "Precondition Failed"
C:/opscode/chef/embedded/lib/ruby/2.5.0/net/http/response.rb:122:in `error!'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/http.rb:152:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/http.rb:131:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:177:in `sync_cookbooks'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:83:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/client.rb:515:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/application/client.rb:444:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/embedded/bin/chef-client:23:in `load'
C:/opscode/chef/embedded/bin/chef-client:23:in `<main>'

Any ideas/suggestions?

**Comment by Annih** [comment]
Hello @cp713a ,
Sorry for the long delay, I hope you have been able to fix your issue since you posted it.

It seems you use the term "package" for chef-cookbooks. your issue is that Chef is unable to find the `windows` cookbook; you may need to upload it to your chef server.
The method to do so depends on your cookbook management - berkshelf, policyfile, etc.

Anyway I don't think this is an issue with the cookbook itself.

That being said, as Chef has deprecated the `windows` cookbook, we might consider removing it from the dependency soon, so such issue would be fixed :)
