### ISSUE TITLE
add .net 4.8 support

### ISSUE THREAD

**Issue by Stromweld** [criteo-cookbooks/ms_dotnet#96]
Feature request
https://dotnet.microsoft.com/download/dotnet-framework/net48

**Comment by bartvff** [comment]
Hello,
While waiting for this feature to be implemented, is it possible to use the cookbook to install .net 4.8 specifying custom `package_sources` or not?
If not, would it be possible to make an estimate as of when this feature will become available?
Thanks

**Comment by jakauppila** [comment]
@Annih Where does #97 sit? I realize that PR only implements partial support for platforms.
Otherwise, I'd like to pick this up and finish it.

**Comment by compuguy** [comment]
It looks to me that PR #97 *should* work with Windows Server 2012R2, Windows 7, WIndows 8.1, Windows 10 & Server 2016 builds 1607, 1709, 1803, and Windows 10 build 1703 via the offline installer provided here (https://support.microsoft.com/en-us/help/4503548/microsoft-net-framework-4-8-offline-installer-for-windows).

**Comment by damfle** [comment]
Should work for mosts Windows versions with PR #98 .

**Comment by Annih** [comment]
A new version is going to be release soon; sorry for the delay!
