### ISSUE TITLE
Download path to .Net 4.7.2 has changed

### ISSUE THREAD

**Issue by BenAkor** [criteo-cookbooks/ms_dotnet#99]
The download path to .net 4.7.2 has changed to https://download.visualstudio.microsoft.com/download/pr/1f5af042-d0e4-4002-9c59-9ba66bcf15f6/089f837de42708daacaae7c04b7494db/ndp472-kb4054530-x86-x64-allos-enu.exe. 

The current path in [here](https://github.com/criteo-cookbooks/ms_dotnet/blob/3a444d1c5b26c186da8227f6e281e8984fbe0832/libraries/package_helper.rb#L111) needs to be adjusted to the new path. Could you kindly adjust the path in the package_helper?
It is also possible the path for all of the previous versions have been changed as well.

**Comment by Annih** [comment]
Fixed by #101; it will be released soon.

**Comment by BenAkor** [comment]
> Fixed by #101; it will be released soon.

@Annih This is yet to be release and it is causing alot of broken pipelines. Can it be released?

**Comment by BenAkor** [comment]
> Fixed by #101; it will be released soon.

The version and changelog were not bumped up.
